/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_albemuth_tentura_util_KeySortContext */

#ifndef _Included_ru_albemuth_tentura_util_KeySortContext
#define _Included_ru_albemuth_tentura_util_KeySortContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_albemuth_tentura_util_KeySortContext
 * Method:    init
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_ru_albemuth_tentura_util_KeySortContext_init
    (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     ru_albemuth_tentura_util_KeySortContext
 * Method:    free
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_albemuth_tentura_util_KeySortContext_free
    (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
