/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_albemuth_tentura_util_Sorting */

#ifndef _Included_ru_albemuth_tentura_util_Sorting
#define _Included_ru_albemuth_tentura_util_Sorting
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_albemuth_tentura_util_Sorting
 * Method:    sortNative
 * Signature: (Ljcuda/driver/CUdeviceptr;IILru/albemuth/tentura/util/KeySortContext;)I
 */
JNIEXPORT jint JNICALL Java_ru_albemuth_tentura_util_Sorting_sortNative__Ljcuda_driver_CUdeviceptr_2IILru_albemuth_tentura_util_KeySortContext_2
    (JNIEnv *, jclass, jobject, jint, jint, jobject);

/*
 * Class:     ru_albemuth_tentura_util_Sorting
 * Method:    sortNative
 * Signature: (Ljcuda/driver/CUdeviceptr;II)I
 */
JNIEXPORT jint JNICALL Java_ru_albemuth_tentura_util_Sorting_sortNative__Ljcuda_driver_CUdeviceptr_2II
    (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     ru_albemuth_tentura_util_Sorting
 * Method:    sortNative
 * Signature: (Ljcuda/driver/CUdeviceptr;ILjcuda/driver/CUdeviceptr;IILru/albemuth/tentura/util/KeyValueSortContext;)I
 */
JNIEXPORT jint JNICALL Java_ru_albemuth_tentura_util_Sorting_sortNative__Ljcuda_driver_CUdeviceptr_2ILjcuda_driver_CUdeviceptr_2IILru_albemuth_tentura_util_KeyValueSortContext_2
    (JNIEnv *, jclass, jobject, jint, jobject, jint, jint, jobject);

/*
 * Class:     ru_albemuth_tentura_util_Sorting
 * Method:    sortNative
 * Signature: (Ljcuda/driver/CUdeviceptr;ILjcuda/driver/CUdeviceptr;II)I
 */
JNIEXPORT jint JNICALL Java_ru_albemuth_tentura_util_Sorting_sortNative__Ljcuda_driver_CUdeviceptr_2ILjcuda_driver_CUdeviceptr_2II
    (JNIEnv *, jclass, jobject, jint, jobject, jint, jint);

/*
 * Class:     ru_albemuth_tentura_util_Sorting
 * Method:    sortNative
 * Signature: (Ljcuda/driver/CUdeviceptr;IIILru/albemuth/tentura/util/KeySortContext;)I
 */
JNIEXPORT jint JNICALL Java_ru_albemuth_tentura_util_Sorting_sortNative__Ljcuda_driver_CUdeviceptr_2IIILru_albemuth_tentura_util_KeySortContext_2
    (JNIEnv *, jclass, jobject, jint, jint, jint, jobject);

/*
 * Class:     ru_albemuth_tentura_util_Sorting
 * Method:    sortNative
 * Signature: (Ljcuda/driver/CUdeviceptr;III)I
 */
JNIEXPORT jint JNICALL Java_ru_albemuth_tentura_util_Sorting_sortNative__Ljcuda_driver_CUdeviceptr_2III
    (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     ru_albemuth_tentura_util_Sorting
 * Method:    sortNative
 * Signature: (Ljcuda/driver/CUdeviceptr;ILjcuda/driver/CUdeviceptr;IIILru/albemuth/tentura/util/KeyValueSortContext;)I
 */
JNIEXPORT jint JNICALL Java_ru_albemuth_tentura_util_Sorting_sortNative__Ljcuda_driver_CUdeviceptr_2ILjcuda_driver_CUdeviceptr_2IIILru_albemuth_tentura_util_KeyValueSortContext_2
    (JNIEnv *, jclass, jobject, jint, jobject, jint, jint, jint, jobject);

/*
 * Class:     ru_albemuth_tentura_util_Sorting
 * Method:    sortNative
 * Signature: (Ljcuda/driver/CUdeviceptr;ILjcuda/driver/CUdeviceptr;III)I
 */
JNIEXPORT jint JNICALL Java_ru_albemuth_tentura_util_Sorting_sortNative__Ljcuda_driver_CUdeviceptr_2ILjcuda_driver_CUdeviceptr_2III
    (JNIEnv *, jclass, jobject, jint, jobject, jint, jint, jint);

/*
 * Class:     ru_albemuth_tentura_util_Sorting
 * Method:    sortNative
 * Signature: (Ljcuda/driver/CUdeviceptr;IILjcuda/driver/CUdeviceptr;ILru/albemuth/tentura/util/KeySortContext;)I
 */
JNIEXPORT jint JNICALL Java_ru_albemuth_tentura_util_Sorting_sortNative__Ljcuda_driver_CUdeviceptr_2IILjcuda_driver_CUdeviceptr_2ILru_albemuth_tentura_util_KeySortContext_2
    (JNIEnv *, jclass, jobject, jint, jint, jobject, jint, jobject);

/*
 * Class:     ru_albemuth_tentura_util_Sorting
 * Method:    sortNative
 * Signature: (Ljcuda/driver/CUdeviceptr;IILjcuda/driver/CUdeviceptr;I)I
 */
JNIEXPORT jint JNICALL Java_ru_albemuth_tentura_util_Sorting_sortNative__Ljcuda_driver_CUdeviceptr_2IILjcuda_driver_CUdeviceptr_2I
    (JNIEnv *, jclass, jobject, jint, jint, jobject, jint);

/*
 * Class:     ru_albemuth_tentura_util_Sorting
 * Method:    sortNative
 * Signature: (Ljcuda/driver/CUdeviceptr;ILjcuda/driver/CUdeviceptr;IILjcuda/driver/CUdeviceptr;ILru/albemuth/tentura/util/KeyValueSortContext;)I
 */
JNIEXPORT jint JNICALL Java_ru_albemuth_tentura_util_Sorting_sortNative__Ljcuda_driver_CUdeviceptr_2ILjcuda_driver_CUdeviceptr_2IILjcuda_driver_CUdeviceptr_2ILru_albemuth_tentura_util_KeyValueSortContext_2
    (JNIEnv *, jclass, jobject, jint, jobject, jint, jint, jobject, jint, jobject);

/*
 * Class:     ru_albemuth_tentura_util_Sorting
 * Method:    sortNative
 * Signature: (Ljcuda/driver/CUdeviceptr;ILjcuda/driver/CUdeviceptr;IILjcuda/driver/CUdeviceptr;I)I
 */
JNIEXPORT jint JNICALL Java_ru_albemuth_tentura_util_Sorting_sortNative__Ljcuda_driver_CUdeviceptr_2ILjcuda_driver_CUdeviceptr_2IILjcuda_driver_CUdeviceptr_2I
    (JNIEnv *, jclass, jobject, jint, jobject, jint, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
